server:
  port: 8888
  mode: debug
app:
  name: interestBar
  version: v1.0.0
log:
  level: debug
  format: console
  director: ./logs
pgsql:
  path: 192.168.200.132
  port: 3367
  config: sslmode=disable TimeZone=Asia/Shanghai
  db_name: interestBar
  username: postgres
  password: password
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: debug
