server:
  port: 8888
  mode: debug
app:
  name: interestBar
  version: v1.0.0
log:
  level: debug
  format: console
  director: ./logs
pgsql:
  path: 192.168.200.132
  port: 3367
  config: sslmode=disable TimeZone=Asia/Shanghai
  db_name: interest_bar_DB
  username: root
  password: 1q2w3e4r5t
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: debug
oauth:
  google:
    client_id: "xxx"
    client_secret: "xxx"
    redirect_url: "https://your_domain/auth/google/callback"
redis:
  host: "192.168.200.132"
  port: 6389
  password: ""
  db: 0
  pool_size: 10
jwt_secret: "change_this_to_a_secure_random_string_at_least_32_characters_long"
